//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 09:06:47 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.exceltoobject4j.myamoto.com/tableObjectMapping", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.myamoto.exceltoobject4j.tableobjectmapping;
