//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 09:06:47 PM CEST 
//


package com.myamoto.exceltoobject4j.tableobjectmapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tableObjectMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tableObjectMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="typeMapper" type="{http://www.exceltoobject4j.myamoto.com/tableObjectMapping}typeMapper" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tableObjectMapping", propOrder = {
    "typeMapper"
})
public class TableObjectMapping {

    protected List<TypeMapper> typeMapper;

    /**
     * Gets the value of the typeMapper property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeMapper property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeMapper().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeMapper }
     * 
     * 
     */
    public List<TypeMapper> getTypeMapper() {
        if (typeMapper == null) {
            typeMapper = new ArrayList<TypeMapper>();
        }
        return this.typeMapper;
    }

	@Override
	public String toString() {
		return "TableObjectMapping [typeMapper=" + typeMapper + "]";
	}
    
}
